# Initial Example
version: 2
jobs:
  build:
    docker:
      - image: python:3.6-alpine
    steps:
      - checkout
      - run: python -V
      - run: ls -lha && pwd
  test:
    docker:
      - image: centos:7
    steps:
      - checkout
      - run: python3 blockchain.py & 
      - run: netstat -pntl
      - run: ps auxw | grep py
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
