# Initial Example
version: 2
jobs:
  build:
    docker:
      - image: python:3.6-alpine
    steps:
      - checkout
      - run: python -V
      - run: ls -lha && pwd
  test:
    docker:
      - image: circleci/python:3.6-alpine
    steps:
      - checkout
      - run: python -V
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
